-- 01 — Criar schemas
DROP SCHEMA IF EXISTS public CASCADE;
DROP SCHEMA IF EXISTS datamart CASCADE;
DROP SCHEMA IF EXISTS dw CASCADE;
DROP SCHEMA IF EXISTS repositorio CASCADE;

CREATE SCHEMA repositorio;
CREATE SCHEMA dw;
CREATE SCHEMA datamart;